version: '3.7'
services:
  
  ## MinIO 1
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY= ${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY= ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data
    networks:
      - web
  ## MinIO 2
  minio2:
    image: minio/minio:latest
    container_name: minio2
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - ../minio2:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server --console-address ":9001" /data
    networks:
      - web
### MinIO

  minio-client:
    image: minio/mc:latest
    container_name: client-minio
    #entrypoint: ["/bin/bash", "/one-way-replication.sh"]
    entrypoint: ["/bin/bash", "/root/two-way-replication.sh"]
    volumes:
      - ./init.sh:/init.sh
      - ./init-config.sh:/init-config.sh
      - ./one-way-replication.sh:/root/one-way-replication.sh
      - ./2wrepl.sh:/root/two-way-replication.sh
      - ./elasticsearch-8.15.2-windows-x86_64.zip:/root/elasticsearch-8.15.2-windows-x86_64.zip
    environment:
      - MC_HOST_minio=http://minio:minio123@minio:9000
      - MC_HOST_minio2=http://minio:minio123@minio2:9000
    depends_on:
      - minio
      - minio2
    networks:
      - web
    
    # nginx
    #nginx:
    #  image: nginx:1.19.2-alpine
    #  hostname: nginx
    #  volumes:
    #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #  ports:
    #    - "9000:9000"
    #    - "9001:9001"
    #  depends_on:
    #    - minio
    #    - minio1
       
networks:
   web:
       driver: bridge
       #external: true